### ISSUE TITLE
facilities: add submit work order feature

### ISSUE THREAD

**Issue by ievans** [dormbase/dormbase#14]
Complete the facilities -> report a problem page such that it either links to or automatically submits a facilities work order.

**Comment by btidor** [comment]
Work orders are submitted via [InsideMIT](https://insidemit-apps.mit.edu/apps/building_services/CreateResidRepairOrder.action?sapSystemId=PS1&pageInfo.bldg1=W71&pageInfo.contactInfo.bldg), an ugly system that was supposed (?) to be shut down last year. Authentication is by certificate only. The user's name is pre-filled into the work order, but they can enter whatever email address they like (for followup and status notifications). It looks like users can access work orders created under a different account so long as they have enough information (order id and building number - or via links in the emails). So, I see two and a half options:
- Get a certificate for dormbase (if this is even possible), and have the system log in and submit work orders on others' behalf, entering their email address so that they get notifications and access
- Figure out who owns InsideMIT and see if they'll let us plug in to the database/API
- Just use a link and have users fill out the form themselves

**Comment by btidor** [comment]
I went with option 3. Once user authentication is set up, we should have it auto-fill the user's room number (and possibly phone number) as well
